### ISSUE TITLE
test doen't compile (ubuntu 18.04 GCC 7.3)

### ISSUE THREAD

**Issue by abar52** [philsquared/textflowcpp#1]
std::copy( col.begin(), col.end(), std::back_inserter( lines ) ); failed to compile (line 160 and 165 in TextFlow_test.cpp) int function to_vector.
FAILED: CMakeFiles/TextFlow.dir/TextFlow_Tests.cpp.o 

/usr/bin/x86_64-linux-gnu-g++-7    -O3 -DNDEBUG   -std=gnu++1z -MD -MT CMakeFiles/TextFlow.dir/TextFlow_Tests.cpp.o -MF CMakeFiles/TextFlow.dir/TextFlow_Tests.cpp.o.d -o CMakeFiles/TextFlow.dir/TextFlow_Tests.cpp.o -c /home/antoine/NetBeansProjects/c++/TextFlow/textflowcpp/TextFlow_Tests.cpp
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /home/antoine/NetBeansProjects/c++/TextFlow/textflowcpp/TextFlow.hpp:14,
                 from /home/antoine/NetBeansProjects/c++/TextFlow/textflowcpp/TextFlow_Tests.cpp:1:
/usr/include/c++/7/bits/stl_algobase.h: In instantiation of ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = TextFlow::Column::iterator; _OI = std::back_insert_iterator<std::vector<std::__cxx11::basic_string<char> > >]’:
/usr/include/c++/7/bits/stl_algobase.h:422:45:   required from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = TextFlow::Column::iterator; _OI = std::back_insert_iterator<std::vector<std::__cxx11::basic_string<char> > >]’
/usr/include/c++/7/bits/stl_algobase.h:455:8:   required from ‘_OI std::copy(_II, _II, _OI) [with _II = TextFlow::Column::iterator; _OI = std::back_insert_iterator<std::vector<std::__cxx11::basic_string<char> > >]’
/home/antoine/NetBeansProjects/c++/TextFlow/textflowcpp/TextFlow_Tests.cpp:160:68:   required from here
/usr/include/c++/7/bits/stl_algobase.h:377:57: error: no type named ‘value_type’ in ‘struct std::iterator_traits<TextFlow::Column::iterator>’
       typedef typename iterator_traits<_II>::value_type _ValueTypeI;
                                                         ^~~~~~~~~~~
/usr/include/c++/7/bits/stl_algobase.h:379:64: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<TextFlow::Column::iterator>’
       typedef typename iterator_traits<_II>::iterator_category _Category;
                                                                ^~~~~~~~~
/usr/include/c++/7/bits/stl_algobase.h:383:9: error: no type named ‘value_type’ in ‘struct std::iterator_traits<TextFlow::Column::iterator>’
       const bool __simple = (__is_trivial(_ValueTypeI)
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
                       && __is_pointer<_II>::__value
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       && __is_pointer<_OI>::__value
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         && __are_same<_ValueTypeI, _ValueTypeO>::__value);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/stl_algobase.h:386:44: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<TextFlow::Column::iterator>’
       return std::__copy_move<_IsMove, __simple,
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        _Category>::__copy_m(__first, __last, __result);
                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

I replace line 160 with:
    for ( auto&& line : col )
        lines.push_back( line );
and line 165 with
    for ( auto&& col : cols )
        lines.push_back( col );
now compile and test PASSED

**Comment by JoeyGrajciar** [comment]
fixed by adding iterator_traits.
https://github.com/philsquared/textflowcpp/commit/41226fcf07148adb2827c72f12a1980beddc692d

**Comment by JoeyGrajciar** [comment]
Closing based on previous comment.
